[package]
name = "boom"
version = "0.1.1"
edition = "2024"

[dependencies]
concat-string = "1.0.1"
ntex = { version = "2.12.3", features = ["tokio"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["ansi"] }
urlencoding = "2.1.3"
