[server]
address = "127.0.0.1"
port = 3000
# Wait for the internet connection to be valid before attempting to serve
wait_for_internet = false
# Whether or not to use SSL; primarily just for http/https in boom-web
is_secure = false # Must be false on 127.0.0.1

[bangs]
# The entirety of `{{{s}}}` will be replaced with the search term
default_search_template = "https://google.com/search?q={{{s}}}"

# Set the path to a default bang file
[[bangs.source]]
# Whether to bother requesting the bangs or not
required = true
filepath = "~/.cache/boom/bangs.json"
# Where to fetch the bangs from
remote = "https://duckduckgo.com/bang.js"

# Existing bangs may be overwritten by their custom equivalent.
# Declaring a bang here is the only way to guarantee that it will be used and not overwritten
# in a race condition between sources.
[bangs.custom]
boomdev = { template = "https://github.com/tobybridle/boom", trigger = "boomdev" }
# ^ shortname

# You can also set them like this
[bangs.custom.amazingdev]
# `!amazedev boom` resolves to the url for this project!
template = "https://github.com/tobybridle/{{{s}}}"
trigger = "amazedev"
